### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by AnaJoselynAlarcon**
updated:   Removed the html tag from schedule layout bc it was causing problems

This PR adds therapist dashboard:

Created dashboard Cards for tracking KPI's

Replaced the previous charts with Apex Charts

The appointment table has a button to display more appointments or collapse.

The sidebar is responsive.

I added a burguer menu for allowing the user to be able to display it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/oribermudez/revitalize/10)

### CODE REVIEW

**Comment by AnaJoselynAlarcon** [comment]
Trying to deploy with errors

**Review by stephaniemartyna — COMMENTED** [review]
Looks good!

> Reviewed 13 of 19 files at r1, 1 of 1 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oribermudez/revitalize/10#-:-NsFwfN91nyxPnaPSKm0:b-vs1prh)* status: 20 of 22 files reviewed, all discussions resolved

**Review by MattYackel — APPROVED** [review]
> Reviewed 14 of 19 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oribermudez/revitalize/10)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AnaJoselynAlarcon)

**Comment by DucPhatNg9a5** [comment]
Look good!

**Pull request merged**
